import { connectDB } from './mongodb';
import {
    User,
    PasswordResetToken,
    Server,
    Notification,
    Log,
    EmailLog,
    Session,
    LoginHistory,
    AuditLog,
    Task,
    Announcement,
    ServerShare,
    TrafficBucket,
    RateLimit,
    SyncRun,
    ServerAssignment,
    Migration,
    type IUser,
    type IPasswordResetToken,
    type IServer,
    type INotification,
    type ILog,
    type IEmailLog,
    type ISession,
    type ILoginHistory,
    type IAuditLog,
    type ITask,
    type IAnnouncement,
    type IServerShare,
    type ITrafficBucket,
    type IRateLimit,
    type ISyncRun,
    type IServerAssignment,
    type IMigration,
    type UserRole,
    type ProviderType,
    type ServerStatusValue,
    type TaskStatusValue,
} from './models';

// Export the connection function
export { connectDB };

// Export all models
export {
    User,
    PasswordResetToken,
    Server,
    Notification,
    Log,
    EmailLog,
    Session,
    LoginHistory,
    AuditLog,
    Task,
    Announcement,
    ServerShare,
    TrafficBucket,
    RateLimit,
    SyncRun,
    ServerAssignment,
    Migration
};

// Export types
export type {
    IUser,
    IPasswordResetToken,
    IServer,
    INotification,
    ILog,
    IEmailLog,
    ISession,
    ILoginHistory,
    IAuditLog,
    ITask,
    IAnnouncement,
    IServerShare,
    ITrafficBucket,
    IRateLimit,
    ISyncRun,
    IServerAssignment,
    IMigration,
    UserRole,
    ProviderType,
    ServerStatusValue,
    TaskStatusValue,
};